**\*\*Задание на повторение материала**

1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [12]:
import numpy as np

In [15]:
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [20]:
a1 = a.reshape(2, 6)
a1

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [21]:
a2 = a.reshape(3, 4)
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [22]:
a3 = a.reshape(4, 3)
a3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [23]:
a4 = a.reshape(6, 2)
a4

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [25]:
a5 = a.reshape(12, 1)
a5

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [27]:
b1 = a.reshape(2, -1)
b1

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [28]:
b2 = a.reshape(3, -1)
b2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [30]:
b3 = a.reshape(4, -1)
b3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [33]:
b4 = a.reshape(-1, 2)
b4

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [35]:
b5 = a.reshape(-1, 1)
b5

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным? - **Нет**

5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [119]:
a = np.random.rand(3, 4)
a

array([[0.35675333, 0.28093451, 0.54269608, 0.14092422],
       [0.80219698, 0.07455064, 0.98688694, 0.77224477],
       [0.19871568, 0.00552212, 0.81546143, 0.70685734]])

In [122]:
b = np.resize(a, (1, 12))
b

array([[0.35675333, 0.28093451, 0.54269608, 0.14092422, 0.80219698,
        0.07455064, 0.98688694, 0.77224477, 0.19871568, 0.00552212,
        0.81546143, 0.70685734]])

6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [38]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

7. Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b? - **a - одномерный, b - двумерный массив**

In [44]:
b = ([[i] for i in range(20, 1, -2)])
b

[[20], [18], [16], [14], [12], [10], [8], [6], [4], [2]]

8. Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [65]:
a = np.zeros((2, 2))
a

array([[0., 0.],
       [0., 0.]])

In [66]:
b = np.ones((3, 2))
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [67]:
v = np.vstack((a, b))
v.size

10

9. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. 

Какой размер имеет матрица B? - **(4, 4)**

Получится ли вычислить обратную матрицу для матрицы B и почему? - **не получится потому, что матрица является сингулярной**

In [79]:
a = [i for i in range(12)]
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [84]:
A = np.array(a).reshape(4, 3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [86]:
At = A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [101]:
B = np.dot(A, At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [92]:
np.linalg.det(B)

0.0

10. Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [95]:
np.random.seed(42)

In [96]:
np.random.randint(0, 10, 3)

array([6, 3, 7])

11. Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 

In [98]:
c = np.linspace(0, 16, 16)
c

array([ 0.        ,  1.06666667,  2.13333333,  3.2       ,  4.26666667,
        5.33333333,  6.4       ,  7.46666667,  8.53333333,  9.6       ,
       10.66666667, 11.73333333, 12.8       , 13.86666667, 14.93333333,
       16.        ])

12. Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [99]:
C = c.reshape(4, 4)
C

array([[ 0.        ,  1.06666667,  2.13333333,  3.2       ],
       [ 4.26666667,  5.33333333,  6.4       ,  7.46666667],
       [ 8.53333333,  9.6       , 10.66666667, 11.73333333],
       [12.8       , 13.86666667, 14.93333333, 16.        ]])

In [100]:
D = (C + B) * 10
D

array([[  50.        ,  150.66666667,  251.33333333,  352.        ],
       [ 182.66666667,  553.33333333,  924.        , 1294.66666667],
       [ 315.33333333,  956.        , 1596.66666667, 2237.33333333],
       [ 448.        , 1358.66666667, 2269.33333333, 3180.        ]])

In [102]:
np.linalg.det(D)

6.877726229660524e-24

In [103]:
np.linalg.matrix_rank(D)

2

In [105]:
D_inv = np.linalg.inv(D)
D_inv

array([[-2.39154696e+12,  8.98156844e+12, -1.07884960e+13,
         4.19847452e+12],
       [-5.33255415e+11, -6.80602306e+12,  1.52118124e+13,
        -7.87253389e+12],
       [ 8.24115171e+12, -1.33326592e+13,  1.94186329e+12,
         3.14964421e+12],
       [-5.31634933e+12,  1.11571138e+13, -6.36517965e+12,
         5.24415158e+11]])

13. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [108]:
D_inv[D_inv < 0] = 0
D_inv[D_inv > 0] = 1

In [109]:
D_inv

array([[0., 1., 0., 1.],
       [0., 0., 1., 0.],
       [1., 0., 1., 1.],
       [0., 1., 0., 1.]])

In [110]:
E = np.where(D_inv, B, C)
E

array([[  0.        ,  14.        ,   2.13333333,  32.        ],
       [  4.26666667,   5.33333333,  86.        ,   7.46666667],
       [ 23.        ,   9.6       , 149.        , 212.        ],
       [ 12.8       , 122.        ,  14.93333333, 302.        ]])